---

- debug:
    msg: "-> base only"
  tags: [ print_action ]

- name: Install zkOpenFHE from source
  block:
    - name: Create build folder
      ansible.builtin.file:
        path: /home/ubuntu/code/build
        state: directory

    - name: Build
      ansible.builtin.shell: 
        cmd: cmake ..
        chdir: /home/ubuntu/code/build
